name: Continuous Integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --immutable
      - name: Lint
        run: yarn lint

  Building:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --immutable
      - name: Generate tsconfig.json base
        run: yarn dev:prepare
      - name: Build module
        run: yarn run build

  Testing:
    name: Testing
    runs-on: ubuntu-latest
    needs:
      - Building
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --immutable
      - name: Install Playwright browser
        run: npx playwright@latest install --with-deps
      - name: Run test
        run: yarn run test
