name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: npx changelogithub@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken $NPM_TOKEN
          yarn npm publish
